# Generated by Django 5.2.8 on 2025-12-19 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_post_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_sync_time',
            field=models.DateTimeField(blank=True, help_text='Last time Steam games were synced', null=True),
        ),
        migrations.CreateModel(
            name='SteamGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('playtime_2weeks', models.IntegerField(default=0, help_text='Minutes played in last 2 weeks')),
                ('playtime_forever', models.IntegerField(default=0, help_text='Total minutes played')),
                ('img_icon_url', models.CharField(blank=True, max_length=500, null=True)),
                ('img_logo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steam_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-playtime_2weeks'],
                'unique_together': {('user', 'appid')},
            },
        ),
    ]
