# Generated by Django 5.2.8 on 2025-12-20 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_profile_last_sync_time_steamgame'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('game', 'Game'), ('movie', 'Movie'), ('tv_show', 'TV Show'), ('song', 'Song'), ('book', 'Book')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text="Material icon name (e.g., 'gamepad', 'movie', 'music_note')", max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Content Type',
                'verbose_name_plural': 'Content Types',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='ContentGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post_count', models.IntegerField(default=0, help_text='Number of posts with this genre')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_genres', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='app.contenttype')),
            ],
            options={
                'verbose_name': 'Content Genre',
                'verbose_name_plural': 'Content Genres',
                'ordering': ['-post_count', 'name'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='content_genre',
            field=models.ForeignKey(blank=True, help_text='Genre of the content', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='app.contentgenre'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Type of content this post is about', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='app.contenttype'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-created_at'], name='app_post_author__a536d0_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['content_type', 'content_genre'], name='app_post_content_2a8b39_idx'),
        ),
        migrations.AddIndex(
            model_name='contentgenre',
            index=models.Index(fields=['content_type', 'name'], name='app_content_content_65e421_idx'),
        ),
        migrations.AddIndex(
            model_name='contentgenre',
            index=models.Index(fields=['-post_count'], name='app_content_post_co_f749fc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentgenre',
            unique_together={('content_type', 'slug')},
        ),
    ]
