# Generated by Django 5.2.8 on 2025-12-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_contenttype_alter_post_options_contentgenre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='steam_id',
            field=models.CharField(blank=True, help_text="User's Steam ID for API integration", max_length=50, null=True, unique=True),
        ),
    ]
