# Generated by Django 5.2.8 on 2025-12-26 22:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text="Visitor's email address", max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the email was submitted')),
            ],
            options={
                'verbose_name': 'Contact Email',
                'verbose_name_plural': 'Contact Emails',
                'ordering': ['-created_at'],
            },
        ),
    ]
