# Generated by Django 5.2.8 on 2026-01-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_message', models.CharField(default='Welcome to My Portfolio', help_text='Main welcome heading', max_length=200)),
                ('welcome_subtitle', models.CharField(default='Explore my journey as a passionate backend developer', help_text='Subtitle below welcome message', max_length=300)),
                ('hero_title', models.CharField(default='Backend Developer | Project Coordinator', help_text='Main hero section title', max_length=200)),
                ('hero_subtitle', models.CharField(default='Python | Django | Cloud | Building scalable applications', help_text='Hero section subtitle', max_length=300)),
                ('name', models.CharField(default='Yadnik Gaonkar', help_text='Your name', max_length=100)),
                ('brief_summary', models.TextField(blank=True, default='', help_text='Brief summary about yourself')),
                ('email', models.EmailField(default='Yadnik72@gmail.com', help_text='Your contact email', max_length=254)),
                ('phone', models.CharField(default='+44 7833886545', help_text='Your phone number', max_length=20)),
                ('location', models.CharField(default='Glasgow, UK', help_text='Your location', max_length=100)),
                ('linkedin_link', models.URLField(default='https://www.linkedin.com/in/yadnikgaonkar', help_text='LinkedIn profile URL')),
                ('github_link', models.URLField(default='https://github.com/iamYadnik', help_text='GitHub profile URL')),
                ('resume_link', models.URLField(blank=True, default='/path/to/resume.pdf', help_text='Resume/CV file URL')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
