# Generated by Django 5.2.8 on 2026-01-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(help_text='Job title/position', max_length=200)),
                ('company', models.CharField(help_text='Company name', max_length=200)),
                ('location', models.CharField(help_text='City, Country', max_length=100)),
                ('period', models.CharField(help_text='Time period (e.g., Jan 2024 - Jul 2024)', max_length=100)),
                ('achievements', models.TextField(help_text='One achievement per line. Each line becomes a bullet point.')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide this experience')),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experience',
                'ordering': ['order', '-period'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project name', max_length=200)),
                ('description', models.TextField(help_text='Project description')),
                ('technologies', models.CharField(help_text='Comma-separated list of technologies (e.g., Django, Python, AWS)', max_length=500)),
                ('link', models.URLField(blank=True, help_text='GitHub or live project URL')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_featured', models.BooleanField(default=True, help_text='Show on homepage as featured project')),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide this project')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Skill category (e.g., Programming Languages, Databases)', max_length=100)),
                ('items', models.TextField(help_text='Comma-separated list of skills (e.g., Python, Java, C)')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide this skill category')),
            ],
            options={
                'verbose_name': 'Technical Skill',
                'verbose_name_plural': 'Technical Skills',
                'ordering': ['order', 'category'],
            },
        ),
    ]
